#!/bin/sh
### BEGIN INIT INFO
# Provides:       generate-ssh-hostkeys
# Required-Start: $local_fs
# Required-Stop:  
# Should-Start:   
# Should-Stop:    
# Default-Start:  0 1 2 3 4 5 6
# Default-Stop:
# Description:    Generate ssh host keys if they do not exist
### END INIT INFO

prog=$(basename $0)
logger="logger -t $prog"

ssh-keygen -A

# Output the public keys to the console
# This allows user to get host keys securely through console log
echo "-----BEGIN SSH HOST KEY FINGERPRINTS-----" | $logger
for f in /etc/ssh/ssh_host_*_key.pub; do
	ssh-keygen -l -f $f | $logger
done
echo "------END SSH HOST KEY FINGERPRINTS------" | $logger
